spring:
  application:
    name: student-example
  data:
    mongodb:
      host:  172.17.0.7
      port: 27017
      database: sampledb
      username: admin
      password: secret
      
eureka:
  client:    
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka